
[game]
MAX_LEVELS = 9

[screen]
WIDTH = 800
HEIGHT = 600

[bird]
MIN_VSPEED = 0
MAX_VSPEED = 7.5
JUMP_BOOST = 15
BIRD_MIN_ANGLE = -15
BIRD_MAX_ANGLE = 45
BIRD_LIVES = 3

[pipe]
PIPE_SPEED = 7.5
PIPE_WIDTH = 100